### ISSUE TITLE
UI APIs called from background threads

### ISSUE THREAD

**Issue by NSMyself** [pollfish/ios-sdk-pollfish#3]
FYI in the latest version of your SDK (available via Cocoapods) - 4.3.5 - Xcode 9 reports at least two cases of UIView methods being called in background threads.

<img width="377" alt="screen shot 2018-03-28 at 11 16 36" src="https://user-images.githubusercontent.com/3126462/38023203-86622e4e-3279-11e8-9ff7-74c03d358fa5.png">

**Comment by kaspanvo** [comment]
@NSMyself we are not able to replicate. We are using XCode 9.3 with the latest Pollfish SDK via Cocoa Pods.

We have enabled Main Thread Checker in the Scheme we are using. We have tested in different simulators and devices. Tested also with Deployment Target up to 11.3 Can you please provide more info on how to replicate this?

**Comment by chintan100** [comment]
Hello, 

I'm seeing this issue with latest Pollfish SDK 5.1.0 on Xcode 11 as well. Deployment target iOS 10.0. Have attached a screenshot: 
<img width="375" alt="Screenshot 2019-10-08 at 12 02 37 PM" src="https://user-images.githubusercontent.com/1689870/66372534-d4d2f380-e9c3-11e9-8469-d11b5a7994fa.png">

**Comment by kaspanvo** [comment]
@chintan100 this issue should be fixed with the latest version of the SDK (v5.0.2)
