### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by koblik-zelter** [pollfish/ios-sdk-pollfish#4]
"_OBJC_CLASS_$_PollfishParams", referenced from:
      objc-class-ref in myLib.a(MyController.o)
     (maybe you meant: _OBJC_CLASS_$_PollfishParamsObj)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kaspanvo** [comment]
@koblik-zelter can you provide more info on your build environment? What is your build target? Are you building for device or simulator? Are you using CocoaPods or directly referencing the library? Any info might be useful

**Comment by koblik-zelter** [comment]
In my project ads are optional so Pollfish Framework in my project is optional. When I disable framework, this error appears. Error appears both on the device and on the simulator. I use Xcode 11.3.1, Objective-C. I added framework manually. The same error appears in Your Sample project, when I disable Your Framework. Is it possible to disable Framework from project?

**Comment by koblik-zelter** [comment]
Thank you for response! We have found an error on our part!
